TDF_JOB_ID = 'tdf_job_id'
WFF_JOB_ID = 'wff_job_id'
CWF_JOB_ID = 'cwf_job_id'
IEF_JOB_ID = 'ief_job_id'
NF_JOB_ID = 'nf_job_id'

SCREEN_TRAINS = 0
SCREEN_INDOOR = 1
SCREEN_OUTDOOR = 2
SCREEN_FORECAST_1 = 3
SCREEN_FORECAST_2 = 4
SCREEN_FORECAST_3 = 5
SCREEN_NEWS = 6
